#!/bin/bash

# sourcing
. ./utils

# make sure the user is aware 
user_sure

# check for programs used in the script
check_bins pv cryptsetup openssl xxd blockdev grub-mkconfig yes parted \
           dd sync umount mount mkfs.ext2 grep

# sanity checks
check_root
check_device "$ROOT_DEV"
check_device "$BOOT_DEV"

check_debian_ready

# make sure the key is a full disk
echo $KEY_DEV | grep -q "[0-9]"
if [ $? == 0 ]; then
    echo "key device $KEY_DEV is a partition: expected full disk."
    exit 1
fi

echo "removing all disks from use"
umount_all "$KEY_DEV" && umount_all "$ROOT_DEV" && umount_all "$BOOT_DEV"
if [ $? != 0 ]; then
    echo "could not unmount the disks from the filesystem. to avoid unexpected"
    echo "errors, unmount them before running this script."
    exit 1
fi

echo "formatting $KEY_DEV to msdos, one partition"
yes | parted "$KEY_DEV" mklabel msdos
yes | parted "$KEY_DEV" unit "%" mkpart primary 0 100
sync
yes | mkfs.ext2 "${KEY_DEV}1" 
sync

echo "overwriting $ROOT_DEV with random data"
#overwrite_device "$ROOT_DEV" "$ROOT_DEV_SIZE"

echo "overwriting $BOOT_DEV with random data"
#overwrite_device "$BOOT_DEV" "$BOOT_DEV_SIZE"

echo "creating a random key"
mntdir="$(mktemp -d)"
mount "${KEY_DEV}1" "$mntdir"
if [ -e "$mntdir/key" ]; then
    rm -f "$mntdir/key"
fi
dd if=/dev/urandom bs=$KEY_SIZE count=1 of="$mntdir/key"
sync 

echo "creating an encrypted volume on $ROOT_DEV"
echo "YES" | cryptsetup luksFormat --hash=$HASH_SPEC --cipher=$CIPHER_SPEC --iter-time=$ITER_TIME "$ROOT_DEV" "$mntdir/key"
if [ "$?" != "0" ]; then
    echo "error while running cryptsetup luksFormat."
    exit 1
fi
freshdisk=freshdisk
while [ -e /dev/mapper/$freshdisk ]; do
    let "l=$RANDOM%10" 
    freshdisk="$freshdisk$l"
done
cryptsetup luksOpen "$ROOT_DEV" "$freshdisk" --key-file "$mntdir/key"
umount "$mntdir"
mkfs.ext4 "/dev/mapper/$freshdisk"
sync
mount "/dev/mapper/$freshdisk" "$mntdir"

echo "installing debian"
# TODO: install debian

# done
sync
umount "$mntdir"
cryptsetup luksClose "/dev/mapper/$freshdisk"
